apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend.yaml
- ingress.yaml
namespace: default
images:
- name: asia.gcr.io/kanji-yomoda/frontend
  newTag: 3b90c50be043b02c34e4496d38e2c7fb13affd93
- name: frontend-image
  newName: asia.gcr.io/kanji-yomoda/frontend
  newTag: latest
