apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend.yaml
- ingress.yaml
namespace: default
images:
- name: frontend
  newName: asia.gcr.io/kanji-yomoda/frontend
  newTag: latest
