version: "3.6"

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - 13306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: cms
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

volumes:
  db_data: