name: Frontend workflow
on:
  push:
    paths:
      - "frontend/**"

jobs:
  build:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install
        run: cd frontend; yarn install

      - name: Lint
        run: cd frontend; yarn lint

      - name: Format Check
        run: cd frontend; yarn fmtcheck
