name: Frontend workflow

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 14.x
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 14.x

      - name: Install
        run: cd frontend; npm install

      - name: Lint
        run: cd frontend; npm run lint

      - name: Format Check
        run: cd frontend; npm run fmtcheck

  deploy:
    name: Deploy
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-project-name: kanjiyomoda
          working-directory: ./
