name: Frontend workflow

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: cd frontend; npm install

      - name: Lint
        run: cd frontend; npm run lint

      - name: Format Check
        run: cd frontend; npm run fmtcheck
