name: Main Workflow

on: [push, pull_request]

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build 
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Build
      run: yarn install

    - name: Lint
      run: yarn run lint

    - name: Format
      run: yarn run prettier
